[project]
name = "email-triage-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client>=2.200.0",
    "google-auth-httplib2>=0.4.2",
    "google-auth-oauthlib>=1.4.1",
    "langchain-core>=1.6.1",
    "langchain-google-genai>=4.3.7",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "tavily-python>=0.8.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
